name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create output directory
        run: mkdir -p distname: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:  # Allows manual triggering of the workflow

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Generate Snake Game
          uses: Platane/snk@v3
          with:
            github_user_name: Wasim-Rana
            outputs: dist/snake.svg
            color_snake: "#FF4500"       # Customize snake color (e.g., Orange Red)
            color_dots: "#8BC34A"       # Customize contribution chart blocks (e.g., Light Green)

        - name: Commit and Push Snake Game
          env:
            TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git remote set-url origin https://x-access-token:${TOKEN}@github.com/Wasim-Rana/Wasim-Rana.git
            git add dist/snake.svg
            git commit -m "Generate snake.svg for GitHub profile"
            git push


        - name: Generate Snake Game
          uses: Platane/snk@v2
          
          with:
              github_user_name: Wasim-Rana
              output: dist/github-contribution-grid-snake.svg
          env:
            ACTIONS_STEP_DEBUG: true

        - name: Upload Snake Game
          uses: actions/upload-artifact@v3
          with:
            name: snake-game
            path: dist/github-contribution-grid-snake.svg
