name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Game
        uses: Platane/snk@v2
        with:
          # GitHub user name to use
          # Use the same username as your GitHub account
          github_user_name: Wasim-Rana

          # Output file
          output: dist/github-contribution-grid-snake.svg

      - name: Upload Snake Game
        uses: actions/upload-artifact@v3
        with:
          name: snake-game
          path: dist/github-contribution-grid-snake.svg
